### ISSUE TITLE
Something wrong about the project

### ISSUE THREAD

**Issue by wu-yz** [simplify23/MRN#3]
When I tried to execute demo.py, an error occurred:
ModuleNotFoundError: No module named 'utils'
Then I find the module named 'utils' has gone.
Can you provide the complete code? Thank you very much!

**Comment by simplify23** [comment]
Sorry, the code does not support demo.py. During the training process, the prediction results of the samples will be displayed simultaneously.

**Comment by wu-yz** [comment]
> Sorry, the code does not support demo.py. During the training process, the prediction results of the samples will be displayed simultaneously.

I see. Thank you very much.
